import {
  placementTest,
  beginner,
  elementary,
  preIntermediate,
  intermediate,
  upperIntermediate,
  advanced,
  grammarIcon,
  skillsIcon,
  pronunciationIcon,
  vocabularyIcon,
  automobileIcon,
  businessIcon,
  chemistryIcon,
  codingIcon,
  foodDrinkIcon,
  dentistryIcon,
  gamesIcon,
  geographyIcon,
  workoutIcon,
  hairdressingIcon,
  historyIcon,
  lawIcon,
  jobInterviewIcon,
  medicineIcon,
  travelIcon,
  scienceIcon,
  songsIcon,
  sportsIcon,
  stockMarketIcon,
  technologyIcon,
  examsIcon,
  allInOneIcon,
  miscIcon,
} from "../../../public/assets/img";

export const navBarLinks = [
  {
    label: "COURSES",
    links: [
      {
        imgSrc: placementTest,
        altName: "Book icon",
        link: "/courses/placement-test",
        name: "Placement Test",
      },
      {
        imgSrc: beginner,
        altName: "Book icon",
        link: "/courses/beginner",
        name: "Beginner (A1)",
      },
      {
        imgSrc: elementary,
        altName: "Book icon",
        link: "/courses/elementary",
        name: "Elementary (A2)",
      },
      {
        imgSrc: preIntermediate,
        altName: "Book icon",
        link: "/courses/pre-intermediate",
        name: "Pre-Int. (A2-B1)",
      },
      {
        imgSrc: intermediate,
        altName: "Book icon",
        link: "/courses/intermediate",
        name: "Intermediate (B1)",
      },
      {
        imgSrc: upperIntermediate,
        altName: "Book icon",
        link: "/courses/upper-intermediate",
        name: "Upper-Inter. (B2)",
      },
      {
        imgSrc: advanced,
        altName: "Book icon",
        link: "/courses/advanced",
        name: "Advanced (C1)",
      },
    ],
  },
  {
    label: "EXTRAS",
    links: [
      {
        imgSrc: skillsIcon,
        altName: "Skills icon",
        link: "/extras/skills",
        name: "Skills",
      },
      {
        imgSrc: grammarIcon,
        altName: "Grammar icon",
        link: "/extras/grammar",
        name: "Grammar",
      },
      {
        imgSrc: pronunciationIcon,
        altName: "Pronunciation icon",
        link: "/extras/pronunciation",
        name: "Pronunciation",
      },
      {
        imgSrc: vocabularyIcon,
        altName: "Book a-z icon",
        link: "/extras/vocabulary",
        name: "Vocabulary",
      },
    ],
  },
  {
    label: "SPECIFIC PURPOSES",
    links: [
      {
        imgSrc: automobileIcon,
        altName: "Automobile icon",
        link: "/specific-purposes/automobile",
        name: "Automobile",
      },
      {
        imgSrc: businessIcon,
        altName: "Business icon",
        link: "/specific-purposes/business",
        name: "Business",
      },
      {
        imgSrc: chemistryIcon,
        altName: "Chemistry icon",
        link: "/specific-purposes/chemistry",
        name: "Chemistry",
      },
      {
        imgSrc: codingIcon,
        altName: "Coding icon",
        link: "/specific-purposes/coding",
        name: "Coding",
      },
      {
        imgSrc: foodDrinkIcon,
        altName: "Cooking icon",
        link: "/specific-purposes/food-drink",
        name: "Food / Drink",
      },
      {
        imgSrc: dentistryIcon,
        altName: "Dentistry icon",
        link: "/specific-purposes/dentistry",
        name: "Dentistry",
      },
      {
        imgSrc: gamesIcon,
        altName: "Games icon",
        link: "/specific-purposes/games",
        name: "Games",
      },
      {
        imgSrc: geographyIcon,
        altName: "Geography icon",
        link: "/specific-purposes/geography",
        name: "Geography",
      },
      {
        imgSrc: workoutIcon,
        altName: "Workout icon",
        link: "/specific-purposes/workout",
        name: "Workout",
      },
      {
        imgSrc: hairdressingIcon,
        altName: "Hairdressing icon",
        link: "/specific-purposes/hairdressing",
        name: "Hairdressing",
      },
      {
        imgSrc: historyIcon,
        altName: "History icon",
        link: "/specific-purposes/history",
        name: "History",
      },
      {
        imgSrc: jobInterviewIcon,
        altName: "Job interview icon",
        link: "/specific-purposes/job-interviews",
        name: "Job Interview",
      },
      {
        imgSrc: lawIcon,
        altName: "Law icon",
        link: "/specific-purposes/law",
        name: "Law",
      },
      {
        imgSrc: medicineIcon,
        altName: "Medicine icon",
        link: "/specific-purposes/medicine",
        name: "Medicine",
      },
      {
        imgSrc: travelIcon,
        altName: "Travel icon",
        link: "/specific-purposes/travel",
        name: "Travel",
      },
      {
        imgSrc: scienceIcon,
        altName: "Science icon",
        link: "/specific-purposes/science",
        name: "Science",
      },
      {
        imgSrc: songsIcon,
        width: "25px",
        altName: "Songs icon",
        link: "/specific-purposes/songs",
        name: "Songs",
      },
      {
        imgSrc: sportsIcon,
        altName: "Sports icon",
        link: "/specific-purposes/sports",
        name: "Sports",
      },
      {
        imgSrc: stockMarketIcon,
        altName: "Stock market icon",
        link: "/specific-purposes/stock-market",
        name: "Stock Market",
      },
      {
        imgSrc: technologyIcon,
        altName: "Technology icon",
        link: "/specific-purposes/technology",
        name: "Technology",
      },
      {
        imgSrc: examsIcon,
        altName: "Exam icon",
        link: "/specific-purposes/exams",
        name: "Exams",
      },
      {
        imgSrc: miscIcon,
        altName: "Ellipsis icon",
        link: "/specific-purposes/misc",
        name: "Miscellaneous",
      },
      {
        imgSrc: allInOneIcon,
        altName: "Book a-z icon",
        link: "/specific-purposes/all-in-one",
        name: "all-in-one",
      },
    ],
  },
];
